version: "3"

services:
  app:
    image: node:18-alpine
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      node server.js
